from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^create_account/$', views.create_account, name='create_account'),
    url(r'^splash/$', views.splash, name='splash'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
    url(r'^forgot_password/$', views.forgot_password, name='forgot_password_view'),
    url(r'^verify_password/$', views.verify_password, name='verify_password_view'),
    url(r'^auth/$', views.auth_view),
    url(r'^patient_home/$', views.patient_home, name='patient_home'),
    url(r'^pat_pers-info/$', views.patPI, name='patPI'),
    url(r'^pat_ins-info/$', views.patIns, name='patIns'),
    url(r'^pat_view-medrec/$', views.patViewMedRec, name='patViewMedRec'),
    url(r'^pat_add-medrec/$', views.patAddMedRec, name='patAddMedRec'),
    url(r'^pat_view-medrec/(?P<usr_id>[0-9]+)/(?P<rec_id>[0-9]+)$', views.patMedRecDetail, name='medRecDetail'),
    url(r'^doctor_home/$', views.doctor_home, name='doctor_home'),
    url(r'^doc_view-patients/$', views.docViewPatients, name='docViewPatients'),
    url(r'^doc_view-patients/(?P<usr_id>[0-9]+)$', views.docViewMedRec, name='docViewMedRec'),
    url(r'^doc_view-patients/(?P<usr_id>[0-9]+)/(?P<rec_id>[0-9]+)$', views.docViewMedRecDetail,
                                                                            name='docViewMedRecDetail'),
    url(r'^doc_add-medrec/$', views.docAddMedRec, name='docAddMedRec'),
    url(r'^cstaff_home/$', views.cstaff_home, name='cstaff_home'),
    #url(r'^cstaff_createuser/$', views.cstaff_createuser, name='cstaff_createuser'),
    url(r'^nurse_home/$', views.nurse_home, name='nurse_home'),
    url(r'^lab_home/$', views.lab_home, name='lab_home'),
    url(r'^pharmacy_home/$', views.pharmacy_home, name='pharmacy_home'),
    url(r'^insurance_home/$', views.insurance_home, name='insurance_home'),
    url(r'^user_not_auth/$', views.user_not_auth, name='user_not_auth'),
]
