# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_out', models.BooleanField(default=False)),
                ('unlock_code', models.CharField(default='', max_length=36)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_in', models.CharField(default='', max_length=1)),
                ('dob', models.DateField(default='')),
                ('age', models.IntegerField(default='')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('address', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=20)),
                ('zip', models.IntegerField(default='')),
                ('phone', models.IntegerField(default='')),
                ('ins_name', models.CharField(default='', max_length=30)),
                ('ins_mem_id', models.IntegerField(default='')),
                ('ins_grp_id', models.IntegerField(default='')),
            ],
        ),
    ]
