# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_out', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20, null=True)),
                ('l_name', models.CharField(max_length=30, null=True)),
                ('mid_in', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zip', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
