# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mid_in',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='l_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='personalinfo',
            table='PersonalInfo',
        ),
    ]
