# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emisuser',
            name='unlock_code',
            field=models.CharField(default=b'', max_length=36),
        ),
    ]
